### ISSUE TITLE
macvlan and vMX

### ISSUE THREAD

**Issue by blauwblaatje** [Juniper/OpenJNPR-Container-vMX#16]
I'm not sure if I'm doing something wrong or that it's a bug :) 

The idea is that the fxp0 is connected to a management vlan. On the physical host I've got eth1 connected untagged to a switch in the right vlan. I've created a macvlan with eth1 as a parent. 

This works for an alpine linux container. I can ping an outside host and vice versa.   (note, I've attached this container later, so not via docker-compose)
It doesn't work with my vMX container. 

When tcpdumping on the physical host, I see ping requests coming from the vMX towards the real world and see ping replies coming in on eth1. 
On the vMX however, I don't see the replies. The only thing I see on the vMX are arp packets and broadcast packets, but no unicast. 
On the alpine linux container I do see the unicast ofcourse. 

Now, I'm quite new to docker, so it might be that I'm misinterpreting something, but this should normally work, right?
I have been able to connect two vMX's together with macvlan to do some L2 protocols over the link (lacp and lldp), but why doesn't it work when I connect it to a physical interface?

```
$ docker inspect vmx_01-mgmt 
[
    {
        "Name": "vmx_01-mgmt",
        "Id": "4b61327756c5c977b04e153569c560905f6931071e4f59cd158ee36ef0c8cd35",
        "Created": "2021-02-23T16:22:34.982498718Z",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.45.0/24"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4b2a273f222ec02f32dce5bad2e44ec66710f9b3b0a849068ea647cbf016c4e8": {
                "Name": "infallible_elion",
                "EndpointID": "33cc2792acb7190251b1a7d5b7d24551c1e193698ae3a5374afabfd763cd87db",
                "MacAddress": "02:42:c0:a8:2d:0b",
                "IPv4Address": "192.168.45.11/24",
                "IPv6Address": ""
            },
            "534f5b16aa43a7c17f896c5bb6dc3a28744eadd1f292c85d698211fb8c2ff713": {
                "Name": "vmx_aqplm1-rt001i_1",
                "EndpointID": "2dcd05c6532870acd7deedcd869214b0eed186cbafb7fbc0a4d46ec3e82dd682",
                "MacAddress": "02:42:c0:a8:2d:0a",
                "IPv4Address": "192.168.45.10/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "eth1"
        },
        "Labels": {
            "com.docker.compose.network": "01-mgmt",
            "com.docker.compose.project": "vmx"
        }
    }
]

$ cat docker-compose.yml 
version: "3"

services:

  aqplm1-rt001i:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - ID=aqplm1-rt001i
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-20.4R1.12.qcow2
      - PUBLICKEY=id_rsa.pub
#      - CONFIG=aqplm1-rt001i.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      01-mgmt:
        ipv4_address: 192.168.45.10
      02-bla:

networks:
  01-mgmt:
    driver: macvlan 
    driver_opts:
       parent: eth1
    ipam:
       config:
         - subnet: 192.168.45.0/24
  02-bla:

```

**Comment by mwiget** [comment]
Unfortunately you can't use macvlan for the management port (fxp0) that gets mapped to eth0. The root cause is this line in the launch.sh script of the container: https://github.com/Juniper/OpenJNPR-Container-vMX/blob/21a4ce1e121151b2875a7a7e4d94525f0dcf1fd3/src/launch.sh#L71

Basically the script moves the mac address of eth0 to fxp0 of the VCP VM, then bridges it back to eth0. That works well with veth endpoints (what you get when using Docker mgmt networks), but won't work for macvlan. That's why you only see BUM traffic, but no unicast.

Note, you can use macvlan just fine for revenue ports of the vMX (ge-0/0/x). 

Hope this helps.

**Comment by blauwblaatje** [comment]
Check, that makes sense.  Patched it now up to ge-0/0/0 and it works as expected. 
Thank you.
